### ISSUE TITLE
Can not build in Mac OSx 10.11.3

### ISSUE THREAD

**Issue by xbee** [MiniblockchainProject/Cryptonite#5]
error

```
In file included from ./gstring.hpp:35:
./exception.hpp:109:12: error: thread-local storage is not supported for the current target
    static thread_local uint32_t EXCEPTION_OPTIONS = 0;
           ^
./exception.hpp:121:12: error: thread-local storage is not supported for the current target
    static thread_local exception_handler_fn EXCEPTION_HANDLER = nullptr;
           ^
./exception.hpp:126:12: error: thread-local storage is not supported for the current target
    static thread_local void* EXCEPTION_HANDLER_ARG = nullptr;
           ^
./exception.hpp:215:3: warning: captureBacktrace: I do not know how to capture backtrace
      there. Patches welcome. [-W#warnings]
# warning captureBacktrace: I do not know how to capture backtrace there. Patches welcome.
  ^
4 warnings and 3 errors generated.

```
